# @name newOddeleniaBulk
POST https://localhost:7031/api/oddelenia/bulk
Content-Type: application/json

{{Newoddelenia}}

###

# @name newZamestnanecBulk
POST https://localhost:7031/api/zamestnanec/bulk
Content-Type: application/json

{{NewZamestnanci}}

###

# @name NewFirmyBulk
POST https://localhost:7031/api/firma/bulk
Content-Type: application/json

{{NewFirmy}}

###

# @name NewDivizieBulk
POST https://localhost:7031/api/divizia/bulk
Content-Type: application/json

{{NewDivizie}}

###

# @name NewProjektyBulk
POST https://localhost:7031/api/projekt/bulk
Content-Type: application/json

{{NewProjekty}}
###

# @name NewOddeleniaRCBulk
POST https://localhost:7031/api/oddelenia/bulk
Content-Type: application/json

{{NewoddeleniaRC}}


