@KrosUlohaJH_HostAddress = https://localhost:7031


POST {{KrosUlohaJH_HostAddress}}/api/zamestnanec
Content-Type: application/json

{
  "rodneCislo": "123456/7890",
  "meno": "Roman",
  "priezvisko": "Novák",
  "email": "jan.novak@example.com",
  "titul": "Ing."
}




@rc=string
GET {{KrosUlohaJH_HostAddress}}/api/zamestnanec/{{rc}}

###

GET {{KrosUlohaJH_HostAddress}}/api/zamestnanec?rc=123456/7890

###
