# @name skuska
POST https://localhost:7031/api/zamestnanec
Content-Type: application/json

{
  "rodneCislo": "123456/7890",
  "meno": "Ján",
  "priezvisko": "Novák",
  "email": "jan.novak@example.com",
  "titul": "Ing."
}
