# @name createZamestnanec
POST {{ApiBaseUrl}}/api/zamestnanec
Content-Type: application/json

{{NewZamestnanec}}

###

# @name getZamestnanec
GET {{ApiBaseUrl}}/api/zamestnanec?rc={{GetDeleteZamestnanec}}



