

# @name createZamestnanec
POST {{ApiBaseUrl}}/api/zamestnanec
Content-Type: application/json

{{NewZamestnanec}}

###

# @name deleteUser
Delete {{ApiBaseUrl}}/api/zamestnanec?rc={{DeleteZamestnanec}}



