

# @name createZamestnanec
POST {{ApiBaseUrl}}{{Zamestnanec}}
Content-Type: application/json

{{NewZamestnanec}}

###

# @name deleteUser
Delete {{ApiBaseUrl}}{{Zamestnanec}}?rc={{GetKod}}

###
# @name getUser
GET {{ApiBaseUrl}}{{Zamestnanec}}?rc={{GetKod}}


