# @name newZamestnanec
POST {{ApiBaseUrl}}{{Zamestnanec}}
Content-Type: application/json

{{NewZamestnanec}}


###

# @name updateZamestnanecBulk
POST {{ApiBaseUrl}}{{Zamestnanec}}bulk/
Content-Type: application/json

[
    {
        "RodneCislo": "990401/4834",
        "Meno" : "Skusony",
        "Titul": "Mgr.",
        "Priezvisko": "IDK",
        "OddelenieId": 2,
        "Email" : "SXK.PR@examsple.com",
        "TelefonneCislo" : "+421940123458"
    },
    {
        "RodneCislo": "990401/483",
        "Titul": "Mgr.",
        "OddelenieId": 1
    }
]

###

# @name getUser
GET {{ApiBaseUrl}}{{Zamestnanec}}?rc={{GetKod}}


    TelefonneCislo = "421940123456",
    OddelenieId = 1,



