

# @name createProjekt
POST {{ApiBaseUrl}}{{Projekt}}
Content-Type: application/json

{{newProjekt}}

###

# @name deleteProjekt
Delete {{ApiBaseUrl}}{{Projekt}}{{GetKod}}


###
# @name getProjekt
GET {{ApiBaseUrl}}{{Projekt}}{{GetKod}}

