# @name updateProjekt
POST {{ApiBaseUrl}}{{Projekt}}
Content-Type: application/json

{{newProjekt}}

###

# @name updateProjektBulk
POST {{ApiBaseUrl}}{{Projekt}}bulk
Content-Type: application/json

[
     { 
        "Nazov" : "Skusobny projekt",
        "Kod" : "PRJ-Mars",
        "DiviziaId":"2",
        "VeduciProjektuRC" :"920402/0001"
    },
    {
        "Nazov": "Skusobny projekt2",
        "Kod": "SP2",
        "DiviziaId":"1",
        "VeduciProjektuRC": "970215/457"
    }
]

###

# @name getProjekt
GET {{ApiBaseUrl}}{{Projekt}}{{GetKod}}



