

# @name createDivizia
POST {{ApiBaseUrl}}/api/divizia
Content-Type: application/json

{{newDivizia}}

###

# @name deleteDivizia
Delete {{ApiBaseUrl}}/api/divizia/{{GetKod}}

###

# @name getDivizia
Get {{ApiBaseUrl}}/api/divizia/{{GetKod}}


