# @name updateDivizia
POST {{ApiBaseUrl}}/api/divizia
Content-Type: application/json

{{newDivizia}}

###

# @name updateDiviziaBulk
POST {{ApiBaseUrl}}/api/divizia/bulk
Content-Type: application/json

[
    {  
        "Nazov": "Banka Csob", 
        "Kod": "KS",
        "VeduciRC": "850201/2222",
        "FirmaId": "1"
    },
    {  
        "Nazov": "Skuska Banka", 
        "Kod": "Tatra",
        "VeduciRC": "890315/578",
        "FirmaId": "1"
    }
]


###

# @name getDivizia
Get {{ApiBaseUrl}}/api/divizia/{{GetKod}}

