// <auto-generated />
using KrosUlohaJH.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrosUlohaJH.Migrations
{
    [DbContext(typeof(StrukturaFirmyContext))]
    partial class StrukturaFirmyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KrosUlohaJH.Models.Divizia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FirmaId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeduciRC")
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("VeduciRC");

                    b.ToTable("Divizie");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiaditelRc")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("RiaditelRc")
                        .IsUnique();

                    b.ToTable("Firmy");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Oddelenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjektId")
                        .HasColumnType("int");

                    b.Property<string>("VeduciOddeleniaRc")
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.HasIndex("VeduciOddeleniaRc");

                    b.ToTable("Oddelenia");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Projekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiviziaId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeduciProjektuRC")
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("DiviziaId");

                    b.HasIndex("VeduciProjektuRC");

                    b.ToTable("Projekty");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Zamestnanec", b =>
                {
                    b.Property<string>("RodneCislo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OddelenieId")
                        .HasColumnType("int");

                    b.Property<string>("Priezvisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonneCislo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Titul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RodneCislo");

                    b.HasIndex("OddelenieId");

                    b.ToTable("Zamestnanci");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Divizia", b =>
                {
                    b.HasOne("KrosUlohaJH.Models.Firma", "Firma")
                        .WithMany("Divizie")
                        .HasForeignKey("FirmaId");

                    b.HasOne("KrosUlohaJH.Models.Zamestnanec", "Veduci")
                        .WithMany("VedeneDivizie")
                        .HasForeignKey("VeduciRC");

                    b.Navigation("Firma");

                    b.Navigation("Veduci");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Firma", b =>
                {
                    b.HasOne("KrosUlohaJH.Models.Zamestnanec", "Riaditel")
                        .WithOne()
                        .HasForeignKey("KrosUlohaJH.Models.Firma", "RiaditelRc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Riaditel");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Oddelenie", b =>
                {
                    b.HasOne("KrosUlohaJH.Models.Projekt", "Projekt")
                        .WithMany("Oddelenia")
                        .HasForeignKey("ProjektId");

                    b.HasOne("KrosUlohaJH.Models.Zamestnanec", "VeduciOddelenia")
                        .WithMany("Oddelenia")
                        .HasForeignKey("VeduciOddeleniaRc");

                    b.Navigation("Projekt");

                    b.Navigation("VeduciOddelenia");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Projekt", b =>
                {
                    b.HasOne("KrosUlohaJH.Models.Divizia", "Divizia")
                        .WithMany("Projekty")
                        .HasForeignKey("DiviziaId");

                    b.HasOne("KrosUlohaJH.Models.Zamestnanec", "VeduciProjektu")
                        .WithMany("Projekty")
                        .HasForeignKey("VeduciProjektuRC");

                    b.Navigation("Divizia");

                    b.Navigation("VeduciProjektu");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Zamestnanec", b =>
                {
                    b.HasOne("KrosUlohaJH.Models.Oddelenie", "Oddelenie")
                        .WithMany("Zamestnanci")
                        .HasForeignKey("OddelenieId");

                    b.Navigation("Oddelenie");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Divizia", b =>
                {
                    b.Navigation("Projekty");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Firma", b =>
                {
                    b.Navigation("Divizie");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Oddelenie", b =>
                {
                    b.Navigation("Zamestnanci");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Projekt", b =>
                {
                    b.Navigation("Oddelenia");
                });

            modelBuilder.Entity("KrosUlohaJH.Models.Zamestnanec", b =>
                {
                    b.Navigation("Oddelenia");

                    b.Navigation("Projekty");

                    b.Navigation("VedeneDivizie");
                });
#pragma warning restore 612, 618
        }
    }
}
