

# @name createOddelenie
POST {{ApiBaseUrl}}{{Oddelenie}}
Content-Type: application/json

{{newOddelenie}}

###

# @name deleteOddelenie
Delete {{ApiBaseUrl}}{{Oddelenie}}{{GetKod}}

###

# @name getOddelenie
GET {{ApiBaseUrl}}{{Oddelenie}}{{GetKod}}



