

# @name createOddelenie
POST {{ApiBaseUrl}}/api/oddelenie
Content-Type: application/json

{{newOddelenie}}

###

# @name deleteOddelenie
Delete {{ApiBaseUrl}}/api/oddelenie/{{GetKod}}

###

# @name getOddelenie
GET {{ApiBaseUrl}}/api/oddelenie/{{GetKod}}



