# @name updateOddelenie
POST {{ApiBaseUrl}}/api/oddelenie
Content-Type: application/json

{{newOddelenie}}


###

# @name updateOddelenieBulk
POST {{ApiBaseUrl}}/api/oddelenie/bulk
Content-Type: application/json

[
{
  "Nazov": "Skusobne oddelenie zmenene",
  "Kod": "SO",
  "ProjektId": 2,
  "VeduciOddeleniaRc": "900228/8888"
},
 {
  "Nazov": "Skusobne oddelenie 2",
  "Kod": "SO2",
  "ProjektId": 1,
  "VeduciOddeleniaRc": "920402/000"
}
]

###

# @name getOddelenie
Get {{ApiBaseUrl}}/api/oddelenie/{{GetKod}}
