# @name newOddeleniaBulk
POST {{ApiBaseUrl}}{{Oddelenie}}bulk
Content-Type: application/json

{{Newoddelenia}}

###

# @name newZamestnanecBulk
POST {{ApiBaseUrl}}{{Zamestnanec}}bulk
Content-Type: application/json

{{NewZamestnanci}}

###

# @name NewFirmyBulk
POST {{ApiBaseUrl}}{{Firma}}bulk
Content-Type: application/json

{{NewFirmy}}

###

# @name NewDivizieBulk
POST {{ApiBaseUrl}}{{Divizia}}bulk
Content-Type: application/json

{{NewDivizie}}

###

# @name NewProjektyBulk
POST {{ApiBaseUrl}}{{Projekt}}bulk
Content-Type: application/json

{{NewProjekty}}
###

# @name NewOddeleniaRCBulk
POST {{ApiBaseUrl}}{{Oddelenie}}bulk
Content-Type: application/json

{{NewoddeleniaRC}}


