# @name newOddeleniaBulk
POST {{ApiBaseUrl}}/api/oddelenie/bulk
Content-Type: application/json

{{Newoddelenia}}

###

# @name newZamestnanecBulk
POST {{ApiBaseUrl}}/api/zamestnanec/bulk
Content-Type: application/json

{{NewZamestnanci}}

###

# @name NewFirmyBulk
POST {{ApiBaseUrl}}/api/firma/bulk
Content-Type: application/json

{{NewFirmy}}

###

# @name NewDivizieBulk
POST {{ApiBaseUrl}}/api/divizia/bulk
Content-Type: application/json

{{NewDivizie}}

###

# @name NewProjektyBulk
POST {{ApiBaseUrl}}/api/projekt/bulk
Content-Type: application/json

{{NewProjekty}}
###

# @name NewOddeleniaRCBulk
POST {{ApiBaseUrl}}/api/oddelenie/bulk
Content-Type: application/json

{{NewoddeleniaRC}}


