

# @name createFirma
POST {{ApiBaseUrl}}{{Firma}}
Content-Type: application/json

{{newFirma}}

###

# @name deleteFirma
Delete {{ApiBaseUrl}}{{Firma}}{{GetFirma}}

###
# @name getFirma
GET {{ApiBaseUrl}}{{Firma}}{{GetFirma}}


