

# @name createFirma
POST {{ApiBaseUrl}}/api/firma
Content-Type: application/json

{{newFirma}}

###

# @name deleteFirma
Delete {{ApiBaseUrl}}/api/firma/{{GetFirma}}

###
# @name getFirma
GET {{ApiBaseUrl}}/api/firma/{{GetFirma}}


