# @name updateFirma
POST {{ApiBaseUrl}}{{Firma}}
Content-Type: application/json

{{newFirma}}


###

# @name updateFirmaBulk
POST {{ApiBaseUrl}}{{Firma}}bulk
Content-Type: application/json

[
     { 
        "Nazov": "SkuskaFirmy",
        "Kod": "SY",
        "RiaditelRc": "970215/4567"
    },
    {
        "Nazov": "SkuskaFirmy",
        "Kod": "TS",
        "RiaditelRc": "970215/457"
    }
]

###

# @name getFirma
Get {{ApiBaseUrl}}{{Firma}}{{GetKod}}
