# @name updateFirma
POST https://localhost:7031/api/firma
Content-Type: application/json

{ 
    "Nazov": "SkuskaFirmy",
    "Kod": "SF",
    "RiaditelRc": "970215/4567"
}


###

# @name updateFirmaBulk
POST https://localhost:7031/api/firma/bulk
Content-Type: application/json

[
     { 
        "Nazov": "SkuskaFirmy",
        "Kod": "KR",
        "RiaditelRc": "970215/4567"
    },
    {
        "Nazov": "TakyIstySef",
        "Kod": "TS",
        "RiaditelRc": "970215/4567"
    }
]

###


