# @name updateFirma
POST {{ApiBaseUrl}}/api/firma
Content-Type: application/json

{{newFirma}}


###

# @name updateFirmaBulk
POST {{ApiBaseUrl}}/api/firma/bulk
Content-Type: application/json

[
     { 
        "Nazov": "SkuskaFirmy",
        "Kod": "SO",
        "RiaditelRc": "970215/4567"
    },
    {
        "Nazov": "SkuskaFirmy",
        "Kod": "TS",
        "RiaditelRc": "970215/457"
    }
]

###

# @name getFirma
Get {{ApiBaseUrl}}/api/firma/{{GetKod}}